site_name: magic_storage docs
theme:
  font:
    text: "Quicksand"
  name: material
  language: en
  palette:
    - scheme: default
      primary: indygo
      accent: indygo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
repo_url: https://github.com/Argmaster/magic_storage
copyright: Copyright (c) 2022 Krzysztof Wiśniewski
nav:
  - Introduction: index.md
  - Development:
      - Introduction: "develop/introduction.md"
      - Tox environments: "develop/tox_basics.md"
      - Documentation: "develop/docs.md"
      - Formatting code: "develop/formatting.md"
      - Quality checks: "develop/quality_checks.md"
  - How to's:
      - Set up tox for development: "howto/tox_devenv.md"
      - Set up Visual Studio Code: "howto/set_up_vsc.md"
      - Set up environment in VSC: "howto/env_in_vsc.md"
  - Changelog: changelog.md
  - License: license.md
markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - admonition
  - md_in_html
  - mdx_truly_sane_lists
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
plugins:
  - search
  - macros:
      include_dir: .
      module_name: docs/macros
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: true
      enabled: true
