name: Test suite

on:
  push:
    branches: ["main", "feature/**", "hotfix/**"]
  pull_request:
    types: [opened, reopened]
    branches: ["*"]
  workflow_dispatch: {}

jobs:
  python_test_suite:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      max-parallel: 4
      fail-fast: false

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          architecture: "x64"
          cache: pip

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: "x64"
          cache: pip

      - name: Install tox
        run: |
          pip install -r requirements-min.txt

      - name: "Test suite on Python 3.9"
        run: tox -e py39 -vv

      - name: "Test suite on Python 3.10"
        run: tox -e py310 -v

      - name: "Code quality checks"
        run: tox -e check -v

      - name: "Static type checking"
        run: tox -e mypy -v

      - name: "Package creation"
        run: tox -e build -v

      - name: "Documentation build"
        run: tox -e docs -v
